name: liquid_glass_workspace_workspace

packages:
  - packages/*
  - "packages/**/example/"

command:
  version:
    updateGitTagRefs: true
    workspaceChangelog: false
    hooks:
      preCommit: |
        melos run generate
        git add .

scripts:
  analyze:
    run: |
      dart analyze . --fatal-infos
    exec:
      # We are setting the concurrency to 1 because a higher concurrency can crash
      # the analysis server on low performance machines (like GitHub Actions).
      concurrency: 1
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  
  test:select:
    run: flutter test --enable-impeller
    exec:
      failFast: true
      concurrency: 6
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all tests in this project.

  coverage:select:
    run: |
      flutter test --coverage --enable-impeller
    exec:
      failFast: true
      concurrency: 6
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.

  coverage:
    run: melos run coverage:select --no-select
    description: Generate coverage for all packages.

  test-without-goldens:select:
    run: flutter test --enable-impeller --exclude-tags=golden
    exec:
      failFast: true
      concurrency: 6
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages without golden tests.

  test-without-goldens:
    run: melos run test-without-goldens:select --no-select
    description: Run all tests in this project without golden tests.

  update-goldens:select:
    run: flutter test --enable-impeller --tags=golden --update-goldens
    exec:
      failFast: true
      concurrency: 6
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages without golden tests.

    
  update-goldens:
    run: melos run update-goldens:select --no-select
  
  generate:select:
    description: Run code generation for selected packages.
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dependsOn:
        - build_runner

  generate:
    description: Run code generation for all packages.
    run: melos run generate:select --no-select